version: '3'

services:
  app:
    container_name: codebank
    build: .
    ports:
      - '50052:50052'
    volumes:
      - .:/go/src/
    extra_hosts:
      - host.docker.internal:172.17.0.1
