apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio3-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desafio3-app
  template:
    metadata:
      labels:
        app: desafio3-app
    spec:
      containers:
        - name: desafio3-app
          image: ajvideira/imersao-fsfc-desafio3-app:latest
          ports:
            - containerPort: 3000
